#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Local development reads .env.local (see .env.example, drizzle.config.ts, and
# the --env-file-if-exists flags in package.json). Both it and .env are
# gitignored, but only .env.local is the one the app actually loads.
ENV_FILE=".env.local"

TOTAL_STAGES=11

# Held in memory for the migration and seeding stages, and deliberately never
# written to disk: this is the production database, and a .env.local holding it
# is one `pnpm dev` away from working against real data.
PROD_DATABASE_URL=""

banner "Jobfinder: Neon + Vercel provisioning (#20)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Before we start"
say "This provisions the two services the app has assumed since #3 but has"
say "never actually had: a Postgres that outlives your laptop, and somewhere"
say "to run the site."
printf '\n'

if [[ ! -f package.json ]] || ! grep -q '"name": "jobfinder"' package.json; then
  warn "Run this from the root of the jobfinder repo."
  exit 1
fi
say "✓ running in the jobfinder repo"

if command -v pnpm >/dev/null 2>&1; then
  say "✓ pnpm found"
else
  warn "pnpm is required (the migration and seeding stages shell out to it)."
  exit 1
fi

if command -v psql >/dev/null 2>&1; then
  say "✓ psql found (used to verify the production database at the end)"
else
  note "psql not found; the final verification will be skipped"
fi

REPO_REMOTE=$(git remote get-url origin 2>/dev/null || echo "unknown")
note "repo: $REPO_REMOTE"
printf '\n'
note "Nothing here writes GitHub Actions secrets. CI runs against its own"
note "Postgres container and must never depend on a reachable Neon instance."
printf '\n'
pause "Press Enter to begin"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Neon: create the project"
say "Neon is reached over the ordinary Postgres wire protocol, which is why"
say "#3 chose node-postgres over a Neon-specific driver. One connection string"
say "serves production, development and tests."
printf '\n'
open_url "https://console.neon.tech/app/projects"
step "Sign in, then create a new project."
step "Name it 'jobfinder'."
step "Pick a region close to where Vercel will run the app; every query the"
step "  nightly sweep makes pays this distance."
step "Take the newest Postgres version offered."
printf '\n'
note "The default branch Neon creates is your production database."
pause "Created the project? Press Enter"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Neon: create a development branch"
say "A second branch so local development never runs against production data."
say "Neon branches are copy-on-write, so this is close to free."
printf '\n'
open_url "https://console.neon.tech/app/projects"
step "Open the project, then the Branches section."
step "Create a branch named 'development', with the default branch as parent."
printf '\n'
pause "Created the development branch? Press Enter"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Neon: development connection string"
say "This is the one that lands in .env.local and drives 'pnpm dev'."
printf '\n'
open_url "https://console.neon.tech/app/projects"
step "Open the connection details for the project."
step "Switch the branch selector to 'development'."
step "Make sure you copy the POOLED connection string. Its host contains"
step "  '-pooler'. Serverless functions open and drop connections constantly,"
step "  and the direct endpoint runs out of them."
printf '\n'
# Asked into DATABASE_URL itself rather than a scratch name, so re-running
# this wizard offers the value already in .env.local back as the default.
ask_secret DATABASE_URL "Paste the development pooled connection string:"

if [[ -z "$DATABASE_URL" ]]; then
  warn "Nothing pasted; skipping. Set DATABASE_URL in .env.local by hand."
  SKIPPED+=("DATABASE_URL in $ENV_FILE")
else
  if [[ "$DATABASE_URL" != *"-pooler"* ]]; then
    warn "That host has no '-pooler' in it, so it looks like the direct endpoint."
    confirm "Use it anyway?" || { warn "Re-run this stage with the pooled string."; exit 1; }
  fi
  write_env DATABASE_URL "$DATABASE_URL"
fi
printf '\n'
pause "Press Enter to continue"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Apply the migrations to development"
say "The branch made in stage 3 is a copy of production as it stood at that"
say "moment, and production is empty until stage 8. Copy-on-write does not"
say "carry a later migration across to a branch already taken, so development"
say "needs a run of its own. Without it 'pnpm dev' talks to a database with no"
say "tables in it."
printf '\n'

if [[ -z "$DATABASE_URL" ]]; then
  warn "No development connection string, so there is nothing to migrate."
  SKIPPED+=("pnpm db:migrate against development")
# Run it rather than ask. This is the developer's own branch, the migrations
# only add, and drizzle records what it has already applied, so a re-run is a
# no-op. A confirm here is precisely how a re-run leaves development empty.
elif DATABASE_URL="$DATABASE_URL" pnpm db:migrate; then
  printf '\n'
  say "✓ migrations applied to development"
else
  printf '\n'
  warn "Migration failed. Fix it and re-run: pnpm db:migrate"
  SKIPPED+=("pnpm db:migrate against development")
fi

printf '\n'
pause "Press Enter to continue"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Vercel: import the repository"
say "Vercel needs to exist as a project before #17 has anywhere to put the"
say "nightly cron. That is all this stage is for."
printf '\n'
open_url "https://vercel.com/new"
step "Import the jobfinder repository from GitHub."
step "Next.js should be detected; leave the build settings alone."
step "Deploy. The first build has no database configured yet, which is fine:"
step "  the database handle is created lazily, so the build does not need one."
printf '\n'
note "Afterwards, in Settings → Git, confirm the Production Branch is 'main'."
pause "Imported and deployed? Press Enter"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Vercel: point the deployment at production Postgres"
say "Now the production branch's connection string, typed into Vercel."
printf '\n'
open_url "https://console.neon.tech/app/projects"
step "Back in Neon, switch the branch selector to your DEFAULT branch."
step "Copy its POOLED connection string ('-pooler' in the host)."
printf '\n'
ask_secret PROD_DATABASE_URL "Paste the PRODUCTION pooled connection string:"

if [[ -z "$PROD_DATABASE_URL" ]]; then
  warn "Nothing pasted. The remaining stages need it, so they will be skipped."
  SKIPPED+=("DATABASE_URL in Vercel, migrations, and production seeding")
else
  if [[ "$PROD_DATABASE_URL" != *"-pooler"* ]]; then
    warn "No '-pooler' in that host either; it looks like the direct endpoint."
    confirm "Use it anyway?" || exit 1
  fi
  note "Held in memory for the next stages only. It is never written to disk:"
  note "a .env.local holding production is one 'pnpm dev' away from real data."
  printf '\n'
  open_url "https://vercel.com/dashboard"
  step "Open the jobfinder project → Settings → Environment Variables."
  step "Add DATABASE_URL with the string you just pasted."
  step "Tick BOTH Production and Preview, so preview deployments are not"
  step "  quietly running against nothing."
  printf '\n'
  pause "Saved it in Vercel? Press Enter"
fi

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Apply the migrations to production"
say "The production database is empty until this runs. It creates the tables"
say "the app expects: boards, postings, fetch_runs, fetch_tasks."
printf '\n'

if [[ -z "$PROD_DATABASE_URL" ]]; then
  warn "No production connection string, so there is nothing to migrate."
  SKIPPED+=("pnpm db:migrate against production")
elif confirm "Run 'pnpm db:migrate' against production now?"; then
  printf '\n'
  if DATABASE_URL="$PROD_DATABASE_URL" pnpm db:migrate; then
    printf '\n'
    say "✓ migrations applied"
  else
    printf '\n'
    warn "Migration failed. Nothing else here depends on it having worked,"
    warn "so you can fix it and re-run: DATABASE_URL='<prod>' pnpm db:migrate"
    SKIPPED+=("pnpm db:migrate against production")
  fi
else
  SKIPPED+=("pnpm db:migrate against production")
fi

printf '\n'
note "How future migrations get applied, which #20 asks to be written down:"
note "  1. pnpm db:generate       — after editing src/db/schema.ts"
note "  2. commit the generated SQL in drizzle/ alongside the schema change"
note "  3. pnpm db:migrate        — against development, read from .env.local"
note "  4. DATABASE_URL='<prod>' pnpm db:migrate   — after the PR is merged"
note "There is no automatic migration on deploy, deliberately: a migration"
note "that runs itself during a build runs on every preview too."
printf '\n'
pause "Press Enter to continue"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Generate the secrets"
say "Two of them. BETTER_AUTH_SECRET signs session cookies — without it,"
say "better-auth falls back to a default and every session is forgeable."
say "CRON_SECRET lets the app tell a real scheduled invocation from a stranger"
say "hitting the same URL; #17 builds that check."
printf '\n'

AUTH_SECRET="$(_existing BETTER_AUTH_SECRET || true)"
if [[ -z "$AUTH_SECRET" ]] && command -v openssl >/dev/null 2>&1; then
  AUTH_SECRET=$(openssl rand -hex 32)
fi

if [[ -n "$AUTH_SECRET" ]]; then
  write_env BETTER_AUTH_SECRET "$AUTH_SECRET"
  printf '\n'
  say "BETTER_AUTH_SECRET, to paste into Vercel:"
  printf '\n    %s%s%s\n\n' "$BOLD" "$AUTH_SECRET" "$RESET"
  note "Changing this later logs everybody out; it is what existing session"
  note "cookies were signed with."
  printf '\n'
else
  SKIPPED+=("BETTER_AUTH_SECRET (generate one: openssl rand -hex 32)")
fi

CRON_SECRET="$(_existing CRON_SECRET || true)"

if [[ -n "$CRON_SECRET" ]]; then
  say "✓ .env.local already holds a CRON_SECRET"
  note "Generating a new one invalidates whatever Vercel is holding, so the"
  note "scheduler would start being turned away until you update it there too."
  confirm "Replace it with a new one?" && CRON_SECRET=""
  printf '\n'
fi

if [[ -z "$CRON_SECRET" ]]; then
  if command -v openssl >/dev/null 2>&1; then
    CRON_SECRET=$(openssl rand -hex 32)
    say "✓ generated a 32-byte secret"
  else
    warn "openssl not found; paste a long random string of your own."
    ask_secret CRON_SECRET "Cron secret:"
  fi
fi

if [[ -n "${CRON_SECRET:-}" ]]; then
  write_env CRON_SECRET "$CRON_SECRET"
  printf '\n'
  say "Its value, to paste into Vercel:"
  printf '\n    %s%s%s\n\n' "$BOLD" "$CRON_SECRET" "$RESET"
  open_url "https://vercel.com/dashboard"
  step "Project → Settings → Environment Variables."
  step "Add BETTER_AUTH_SECRET and CRON_SECRET with the values above,"
  step "  both ticked for Production. Tick Preview for BETTER_AUTH_SECRET too,"
  step "  or preview deployments cannot sign anyone in."
  step "Add BETTER_AUTH_URL as well, set to the deployment's own https URL."
  step "  Without it the origin comes from the request's Host header, which is"
  step "  fine locally and not something to trust once deployed."
  printf '\n'
  note "Vercel sends CRON_SECRET as a Bearer token on cron invocations, so #17"
  note "can check the header rather than trusting whoever called the endpoint."
  printf '\n'
  pause "Saved them in Vercel? Press Enter"
fi

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Verify"
say "Two things are checkable now, and one is not."
printf '\n'
ask DEPLOYED_URL "Your deployment's URL (https://…):"
if [[ -n "$DEPLOYED_URL" ]]; then
  open_url "$DEPLOYED_URL"
fi
step "Confirm the page loads."
printf '\n'

if [[ -n "$PROD_DATABASE_URL" ]] && command -v psql >/dev/null 2>&1; then
  say "Checking the production database is reachable and migrated…"
  printf '\n'
  if psql "$PROD_DATABASE_URL" -c "\dt" 2>&1 | sed 's/^/    /'; then
    printf '\n'
    say "✓ production database answers, and those are its tables"
  else
    warn "Could not query production. Check the connection string."
  fi
else
  note "Skipping the database check (needs psql and the production string)."
fi

printf '\n'
warn "What cannot be verified yet: that the DEPLOYED APP reaches the database."
note "Nothing rendered by the site queries it — the dashboard is #9 and the"
note "cron endpoint is #17. Both halves are proven above, but the join between"
note "them is not, so treat that acceptance criterion as pending until #9 or"
note "#17 puts a real query behind a request."
printf '\n'
pause "Press Enter to continue"

# ── 11 ────────────────────────────────────────────────────────────────────
stage "Optional: seed the curated set into production"
say "The 236 Boards from #18 currently exist only in your local test database,"
say "which every test run wipes. This writes them somewhere permanent."
printf '\n'
note "It probes all 236 Boards against the live Greenhouse API first, so it"
note "takes a few minutes and makes real network requests."
printf '\n'

if [[ -z "$PROD_DATABASE_URL" ]]; then
  warn "No production connection string, so skipping."
  SKIPPED+=("pnpm seed:boards against production")
elif confirm "Seed the curated set into production now?"; then
  printf '\n'
  if DATABASE_URL="$PROD_DATABASE_URL" pnpm seed:boards; then
    printf '\n'
    say "✓ the curated set is in production"
  else
    warn "Seeding failed; re-run later with DATABASE_URL='<prod>' pnpm seed:boards"
    SKIPPED+=("pnpm seed:boards against production")
  fi
else
  note "Run it whenever you like: DATABASE_URL='<prod>' pnpm seed:boards"
fi

finish

note "The Corpus is still empty: Postings arrive when a Fetch actually runs,"
note "and the nightly cron that triggers one is #17. Until then you can fill"
note "it by hand with DATABASE_URL='<prod>' and a Fetch run of your own."
printf '\n'
